name: Update pages

on:
  push:
    branches:
      - master

jobs:
  release_chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Publish Helm Charts on GitHub Pages with chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
      - name: Publish the Helm Chart demo-backend to my ChartMuseum
        uses: bsord/helm-push@v3
        with:
          username: ${{ secrets.HELM_USERNAME }}
          password: ${{ secrets.HELM_PASSWORD }}
          repository-url: ${{ secrets.HARBOR_MUSEUM_URL }}
          force: true
          chart-folder: charts/demo-backend

    
