name: Update pages

on:
  push:
    branches:
      - master

jobs:
  release_to_github_pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
  release_to_chart_museum:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: goodsmileduck/helm-push-action@v2
      env:
        SOURCE_DIR: 'charts'
        CHART_FOLDER: './charts'
        FORCE: 'True'
        CHARTMUSEUM_URL: '${{ secrets.CHARTMUSEUM_URL }}'
        CHARTMUSEUM_USER: '${{ secrets.CHARTMUSEUM_USER }}'
        CHARTMUSEUM_PASSWORD: '${{ secrets.CHARTMUSEUM_PASSWORD }}'  
